/**
 * Item Definitions for RogueDemo
 * 50 items across 5 tiers with varied fantasy-themed stats
 */

import { ItemDefinition } from './types';

export const ITEMS: ItemDefinition[] = [
  // ========== TIER 1: COMMON (Gray/Brown) ==========
  {
    id: 'rusty_sword',
    name: 'Rusty Sword',
    tier: 1,
    stats: {
      raw_attack: 5,
      attack_speed: 0.1,
    },
    color: '#8B4513',
    description: 'A worn blade that has seen better days.',
  },
  {
    id: 'leather_cap',
    name: 'Leather Cap',
    tier: 1,
    stats: {
      armour: 3,
      move_speed: 5,
    },
    color: '#A0522D',
    description: 'Basic leather headgear for minimal protection.',
  },
  {
    id: 'wooden_shield',
    name: 'Wooden Shield',
    tier: 1,
    stats: {
      armour: 5,
      damage_block: 2,
    },
    color: '#8B7355',
    description: 'A simple wooden shield for blocking blows.',
  },
  {
    id: 'cloth_boots',
    name: 'Cloth Boots',
    tier: 1,
    stats: {
      move_speed: 10,
      armour: 1,
    },
    color: '#696969',
    description: 'Light footwear for basic mobility.',
  },
  {
    id: 'iron_ring',
    name: 'Iron Ring',
    tier: 1,
    stats: {
      raw_attack: 3,
      armour: 2,
    },
    color: '#808080',
    description: 'A simple iron band with minor enchantment.',
  },
  {
    id: 'cracked_wand',
    name: 'Cracked Wand',
    tier: 1,
    stats: {
      raw_spell: 6,
      magic_res: 2,
    },
    color: '#8B8378',
    description: 'A damaged magical focus with weak power.',
  },
  {
    id: 'padded_vest',
    name: 'Padded Vest',
    tier: 1,
    stats: {
      armour: 4,
      magic_res: 2,
    },
    color: '#A9A9A9',
    description: 'Quilted cloth providing modest protection.',
  },
  {
    id: 'bone_charm',
    name: 'Bone Charm',
    tier: 1,
    stats: {
      raw_spell: 4,
      increased_damage: 2,
    },
    color: '#F5F5DC',
    description: 'A carved bone trinket with faint magic.',
  },
  {
    id: 'tattered_cloak',
    name: 'Tattered Cloak',
    tier: 1,
    stats: {
      move_speed: 8,
      magic_res: 3,
    },
    color: '#778899',
    description: 'A worn cloak offering slight magical protection.',
  },
  {
    id: 'simple_bracelet',
    name: 'Simple Bracelet',
    tier: 1,
    stats: {
      attack_speed: 0.05,
      move_speed: 5,
    },
    color: '#C0C0C0',
    description: 'A plain bracelet with minor agility boost.',
  },

  // ========== TIER 2: UNCOMMON (Green) ==========
  {
    id: 'steel_blade',
    name: 'Steel Blade',
    tier: 2,
    stats: {
      raw_attack: 12,
      attack_speed: 0.15,
      percent_attack_increase: 5,
    },
    color: '#228B22',
    description: 'A well-forged steel sword with keen edge.',
  },
  {
    id: 'chain_mail',
    name: 'Chain Mail',
    tier: 2,
    stats: {
      armour: 12,
      damage_block: 3,
      move_speed: -5,
    },
    color: '#2E8B57',
    description: 'Interlocking metal rings provide solid defense.',
  },
  {
    id: 'tower_shield',
    name: 'Tower Shield',
    tier: 2,
    stats: {
      armour: 15,
      damage_block: 5,
      move_speed: -10,
    },
    color: '#3CB371',
    description: 'A massive shield that blocks heavy attacks.',
  },
  {
    id: 'swift_boots',
    name: 'Swift Boots',
    tier: 2,
    stats: {
      move_speed: 25,
      armour: 3,
      attack_speed: 0.1,
    },
    color: '#32CD32',
    description: 'Enchanted boots that quicken your step.',
  },
  {
    id: 'ruby_ring',
    name: 'Ruby Ring',
    tier: 2,
    stats: {
      raw_attack: 8,
      percent_attack_increase: 8,
      increased_damage: 5,
    },
    color: '#8B0000',
    description: 'A gold ring set with a blood-red ruby.',
  },
  {
    id: 'oak_staff',
    name: 'Oak Staff',
    tier: 2,
    stats: {
      raw_spell: 15,
      percent_spell_increase: 6,
      magic_res: 5,
    },
    color: '#6B8E23',
    description: 'A sturdy staff carved from ancient oak.',
  },
  {
    id: 'reinforced_vest',
    name: 'Reinforced Vest',
    tier: 2,
    stats: {
      armour: 10,
      magic_res: 6,
      damage_block: 3,
    },
    color: '#556B2F',
    description: 'Leather armor reinforced with metal plates.',
  },
  {
    id: 'wolf_fang_necklace',
    name: 'Wolf Fang Necklace',
    tier: 2,
    stats: {
      raw_attack: 10,
      attack_speed: 0.12,
      move_speed: 15,
    },
    color: '#8FBC8F',
    description: 'Wolf teeth strung on leather, blessed by hunters.',
  },
  {
    id: 'travelers_cloak',
    name: "Traveler's Cloak",
    tier: 2,
    stats: {
      move_speed: 20,
      magic_res: 8,
      armour: 4,
    },
    color: '#90EE90',
    description: 'A weathered cloak worn by seasoned adventurers.',
  },
  {
    id: 'silver_bracelet',
    name: 'Silver Bracelet',
    tier: 2,
    stats: {
      raw_spell: 10,
      attack_speed: 0.08,
      increased_damage: 4,
    },
    color: '#98FB98',
    description: 'Silver inscribed with protective runes.',
  },

  // ========== TIER 3: RARE (Blue) ==========
  {
    id: 'flamebrand',
    name: 'Flamebrand',
    tier: 3,
    stats: {
      raw_attack: 25,
      percent_attack_increase: 15,
      increased_damage: 10,
      attack_speed: 0.2,
    },
    color: '#4169E1',
    description: 'A sword wreathed in eternal flames.',
  },
  {
    id: 'mithril_plate',
    name: 'Mithril Plate',
    tier: 3,
    stats: {
      armour: 25,
      magic_res: 12,
      damage_block: 8,
    },
    color: '#1E90FF',
    description: 'Light yet incredibly strong armor of mithril.',
  },
  {
    id: 'aegis_guard',
    name: 'Aegis Guard',
    tier: 3,
    stats: {
      armour: 28,
      damage_block: 10,
      magic_res: 15,
    },
    color: '#6495ED',
    description: 'A legendary shield blessed by divine power.',
  },
  {
    id: 'windwalker_boots',
    name: 'Windwalker Boots',
    tier: 3,
    stats: {
      move_speed: 45,
      attack_speed: 0.18,
      armour: 6,
    },
    color: '#00BFFF',
    description: 'Boots that let you dance on the wind.',
  },
  {
    id: 'emerald_signet',
    name: 'Emerald Signet',
    tier: 3,
    stats: {
      raw_spell: 20,
      percent_spell_increase: 18,
      magic_res: 10,
      increased_damage: 8,
    },
    color: '#4682B4',
    description: 'A noble ring channeling nature magic.',
  },
  {
    id: 'crystal_orb',
    name: 'Crystal Orb',
    tier: 3,
    stats: {
      raw_spell: 30,
      percent_spell_increase: 20,
      magic_res: 18,
    },
    color: '#87CEEB',
    description: 'A perfectly clear orb pulsing with arcane energy.',
  },
  {
    id: 'dragonhide_vest',
    name: 'Dragonhide Vest',
    tier: 3,
    stats: {
      armour: 22,
      magic_res: 20,
      damage_block: 7,
      move_speed: 10,
    },
    color: '#4682B4',
    description: 'Armor crafted from the hide of a dragon.',
  },
  {
    id: 'amulet_of_storms',
    name: 'Amulet of Storms',
    tier: 3,
    stats: {
      raw_spell: 25,
      percent_spell_increase: 15,
      increased_damage: 12,
    },
    color: '#5F9EA0',
    description: 'An amulet crackling with lightning energy.',
  },
  {
    id: 'shadow_cloak',
    name: 'Shadow Cloak',
    tier: 3,
    stats: {
      move_speed: 35,
      magic_res: 16,
      armour: 10,
      attack_speed: 0.15,
    },
    color: '#483D8B',
    description: 'A cloak woven from shadows themselves.',
  },
  {
    id: 'enchanted_gauntlets',
    name: 'Enchanted Gauntlets',
    tier: 3,
    stats: {
      raw_attack: 18,
      raw_spell: 18,
      attack_speed: 0.2,
      damage_block: 5,
    },
    color: '#6A5ACD',
    description: 'Gauntlets enhancing both martial and magical prowess.',
  },

  // ========== TIER 4: EPIC (Purple) ==========
  {
    id: 'demonslayer',
    name: 'Demonslayer',
    tier: 4,
    stats: {
      raw_attack: 45,
      percent_attack_increase: 30,
      increased_damage: 20,
      attack_speed: 0.3,
    },
    color: '#8B008B',
    description: 'A holy blade forged to destroy evil.',
  },
  {
    id: 'titanium_fortress',
    name: 'Titanium Fortress',
    tier: 4,
    stats: {
      armour: 45,
      magic_res: 25,
      damage_block: 15,
      move_speed: -5,
    },
    color: '#9400D3',
    description: 'Impenetrable armor made from titanium alloy.',
  },
  {
    id: 'divine_bulwark',
    name: 'Divine Bulwark',
    tier: 4,
    stats: {
      armour: 50,
      damage_block: 18,
      magic_res: 30,
    },
    color: '#9932CC',
    description: 'A shield blessed by the gods themselves.',
  },
  {
    id: 'hermes_sandals',
    name: 'Hermes Sandals',
    tier: 4,
    stats: {
      move_speed: 70,
      attack_speed: 0.35,
      armour: 10,
      magic_res: 15,
    },
    color: '#BA55D3',
    description: 'Divine footwear granting supernatural speed.',
  },
  {
    id: 'ring_of_archmage',
    name: 'Ring of the Archmage',
    tier: 4,
    stats: {
      raw_spell: 40,
      percent_spell_increase: 35,
      magic_res: 20,
      increased_damage: 18,
    },
    color: '#8B008B',
    description: 'A ring once worn by the greatest mage.',
  },
  {
    id: 'void_staff',
    name: 'Void Staff',
    tier: 4,
    stats: {
      raw_spell: 55,
      percent_spell_increase: 40,
      magic_res: 28,
      increased_damage: 15,
    },
    color: '#9370DB',
    description: 'A staff channeling the power of the void.',
  },
  {
    id: 'phoenix_mail',
    name: 'Phoenix Mail',
    tier: 4,
    stats: {
      armour: 38,
      magic_res: 35,
      damage_block: 12,
      move_speed: 20,
    },
    color: '#DA70D6',
    description: 'Armor that burns with regenerating flames.',
  },
  {
    id: 'heart_of_mountain',
    name: 'Heart of the Mountain',
    tier: 4,
    stats: {
      armour: 30,
      damage_block: 20,
      raw_attack: 25,
      magic_res: 25,
    },
    color: '#DDA0DD',
    description: 'An amulet containing the essence of mountains.',
  },
  {
    id: 'cloak_of_stars',
    name: 'Cloak of Stars',
    tier: 4,
    stats: {
      move_speed: 50,
      magic_res: 30,
      armour: 18,
      raw_spell: 30,
    },
    color: '#EE82EE',
    description: 'A celestial cloak shimmering with starlight.',
  },
  {
    id: 'gauntlets_of_thunder',
    name: 'Gauntlets of Thunder',
    tier: 4,
    stats: {
      raw_attack: 35,
      attack_speed: 0.4,
      increased_damage: 22,
      damage_block: 10,
    },
    color: '#9400D3',
    description: 'Gauntlets that strike with thunderous force.',
  },

  // ========== TIER 5: LEGENDARY (Gold/Orange) ==========
  {
    id: 'excalibur',
    name: 'Excalibur',
    tier: 5,
    stats: {
      raw_attack: 80,
      percent_attack_increase: 50,
      increased_damage: 35,
      attack_speed: 0.5,
    },
    color: '#FFD700',
    description: 'The legendary sword of kings, unmatched in power.',
  },
  {
    id: 'armor_of_gods',
    name: 'Armor of the Gods',
    tier: 5,
    stats: {
      armour: 70,
      magic_res: 50,
      damage_block: 25,
      move_speed: 10,
    },
    color: '#FFA500',
    description: 'Divine armor granting near-invulnerability.',
  },
  {
    id: 'unbreakable_wall',
    name: 'Unbreakable Wall',
    tier: 5,
    stats: {
      armour: 80,
      damage_block: 30,
      magic_res: 45,
      raw_attack: 20,
    },
    color: '#FF8C00',
    description: 'A shield that has never been broken.',
  },
  {
    id: 'boots_of_wind_god',
    name: 'Boots of the Wind God',
    tier: 5,
    stats: {
      move_speed: 100,
      attack_speed: 0.6,
      armour: 20,
      magic_res: 25,
    },
    color: '#FFA500',
    description: 'Divine boots granting transcendent speed.',
  },
  {
    id: 'ouroboros_ring',
    name: 'Ouroboros Ring',
    tier: 5,
    stats: {
      raw_attack: 40,
      raw_spell: 40,
      percent_attack_increase: 25,
      percent_spell_increase: 25,
      increased_damage: 30,
    },
    color: '#FFD700',
    description: 'The eternal ring balancing all forms of power.',
  },
  {
    id: 'staff_of_eternity',
    name: 'Staff of Eternity',
    tier: 5,
    stats: {
      raw_spell: 90,
      percent_spell_increase: 60,
      magic_res: 40,
      increased_damage: 28,
    },
    color: '#FF8C00',
    description: 'A staff containing infinite magical energy.',
  },
  {
    id: 'celestial_raiment',
    name: 'Celestial Raiment',
    tier: 5,
    stats: {
      armour: 55,
      magic_res: 60,
      damage_block: 18,
      move_speed: 40,
    },
    color: '#FFAA00',
    description: 'Robes woven from the fabric of the cosmos.',
  },
  {
    id: 'crown_of_dominion',
    name: 'Crown of Dominion',
    tier: 5,
    stats: {
      raw_attack: 50,
      raw_spell: 50,
      increased_damage: 40,
      magic_res: 35,
    },
    color: '#FFD700',
    description: 'A crown that commands absolute authority.',
  },
  {
    id: 'cloak_of_shadows_legendary',
    name: 'Cloak of Shadows',
    tier: 5,
    stats: {
      move_speed: 80,
      magic_res: 45,
      armour: 30,
      attack_speed: 0.4,
    },
    color: '#FF8C00',
    description: 'A cloak granting mastery over darkness.',
  },
  {
    id: 'fists_of_titan',
    name: 'Fists of the Titan',
    tier: 5,
    stats: {
      raw_attack: 70,
      attack_speed: 0.7,
      increased_damage: 35,
      damage_block: 20,
    },
    color: '#FFA500',
    description: 'Gauntlets containing the strength of titans.',
  },
];
