/**
 * Monster Definitions for RogueDemo
 * 20 monster types with increasing difficulty levels
 */

import { MonsterDefinition } from './types';

export const MONSTERS: MonsterDefinition[] = [
  // ========== LEVELS 1-2: Early Game ==========
  {
    type: 'slime',
    name: 'Slime',
    baseHp: 50,
    baseDamage: 5,
    damageType: 'attack',
    baseSpeed: 40,
    baseArmour: 0,
    baseMagicRes: 5,
    chaseRange: 250,
    attackRange: 40,
    attackSpeed: 0.8,
    color: '#32CD32',
    size: 20,
    xpReward: 10,
    minLevel: 1,
    maxLevel: 2,
  },
  {
    type: 'bat',
    name: 'Bat',
    baseHp: 30,
    baseDamage: 8,
    damageType: 'attack',
    baseSpeed: 180,
    baseArmour: 0,
    baseMagicRes: 0,
    chaseRange: 350,
    attackRange: 45,
    attackSpeed: 1.5,
    color: '#4B0082',
    size: 15,
    xpReward: 12,
    minLevel: 1,
    maxLevel: 2,
  },
  {
    type: 'imp',
    name: 'Imp',
    baseHp: 40,
    baseDamage: 10,
    damageType: 'spell',
    baseSpeed: 100,
    baseArmour: 2,
    baseMagicRes: 8,
    chaseRange: 300,
    attackRange: 120,
    attackSpeed: 1.0,
    color: '#DC143C',
    size: 18,
    xpReward: 15,
    minLevel: 1,
    maxLevel: 2,
  },
  {
    type: 'spider',
    name: 'Spider',
    baseHp: 60,
    baseDamage: 7,
    damageType: 'attack',
    baseSpeed: 120,
    baseArmour: 3,
    baseMagicRes: 2,
    chaseRange: 280,
    attackRange: 50,
    attackSpeed: 1.2,
    color: '#8B4513',
    size: 22,
    xpReward: 14,
    minLevel: 1,
    maxLevel: 3,
  },

  // ========== LEVELS 2-3: Early-Mid Game ==========
  {
    type: 'skeleton',
    name: 'Skeleton',
    baseHp: 80,
    baseDamage: 12,
    damageType: 'attack',
    baseSpeed: 90,
    baseArmour: 10,
    baseMagicRes: 5,
    chaseRange: 300,
    attackRange: 50,
    attackSpeed: 0.9,
    color: '#F5F5DC',
    size: 20,
    xpReward: 20,
    minLevel: 2,
    maxLevel: 4,
  },
  {
    type: 'goblin',
    name: 'Goblin',
    baseHp: 70,
    baseDamage: 14,
    damageType: 'attack',
    baseSpeed: 140,
    baseArmour: 5,
    baseMagicRes: 3,
    chaseRange: 320,
    attackRange: 45,
    attackSpeed: 1.4,
    color: '#228B22',
    size: 18,
    xpReward: 22,
    minLevel: 2,
    maxLevel: 4,
  },
  {
    type: 'wolf',
    name: 'Wolf',
    baseHp: 90,
    baseDamage: 16,
    damageType: 'attack',
    baseSpeed: 160,
    baseArmour: 4,
    baseMagicRes: 2,
    chaseRange: 400,
    attackRange: 48,
    attackSpeed: 1.3,
    color: '#696969',
    size: 24,
    xpReward: 25,
    minLevel: 2,
    maxLevel: 4,
  },

  // ========== LEVELS 3-5: Mid Game ==========
  {
    type: 'zombie',
    name: 'Zombie',
    baseHp: 150,
    baseDamage: 18,
    damageType: 'attack',
    baseSpeed: 60,
    baseArmour: 12,
    baseMagicRes: 8,
    chaseRange: 280,
    attackRange: 50,
    attackSpeed: 0.7,
    color: '#556B2F',
    size: 22,
    xpReward: 30,
    minLevel: 3,
    maxLevel: 5,
  },
  {
    type: 'ghost',
    name: 'Ghost',
    baseHp: 100,
    baseDamage: 20,
    damageType: 'spell',
    baseSpeed: 130,
    baseArmour: 0,
    baseMagicRes: 20,
    chaseRange: 350,
    attackRange: 100,
    attackSpeed: 1.1,
    color: '#E0E0E0',
    size: 20,
    xpReward: 35,
    minLevel: 3,
    maxLevel: 5,
  },
  {
    type: 'orc',
    name: 'Orc',
    baseHp: 180,
    baseDamage: 25,
    damageType: 'attack',
    baseSpeed: 100,
    baseArmour: 15,
    baseMagicRes: 5,
    chaseRange: 300,
    attackRange: 55,
    attackSpeed: 0.8,
    color: '#8B7D6B',
    size: 26,
    xpReward: 40,
    minLevel: 3,
    maxLevel: 6,
  },

  // ========== LEVELS 4-6: Mid-Late Game ==========
  {
    type: 'wraith',
    name: 'Wraith',
    baseHp: 120,
    baseDamage: 28,
    damageType: 'spell',
    baseSpeed: 150,
    baseArmour: 5,
    baseMagicRes: 25,
    chaseRange: 360,
    attackRange: 110,
    attackSpeed: 1.2,
    color: '#2F4F4F',
    size: 22,
    xpReward: 50,
    minLevel: 4,
    maxLevel: 7,
  },
  {
    type: 'harpy',
    name: 'Harpy',
    baseHp: 110,
    baseDamage: 22,
    damageType: 'attack',
    baseSpeed: 170,
    baseArmour: 6,
    baseMagicRes: 10,
    chaseRange: 380,
    attackRange: 90,
    attackSpeed: 1.6,
    color: '#9370DB',
    size: 20,
    xpReward: 45,
    minLevel: 4,
    maxLevel: 7,
  },
  {
    type: 'troll',
    name: 'Troll',
    baseHp: 280,
    baseDamage: 30,
    damageType: 'attack',
    baseSpeed: 70,
    baseArmour: 25,
    baseMagicRes: 10,
    chaseRange: 290,
    attackRange: 60,
    attackSpeed: 0.6,
    color: '#2E8B57',
    size: 32,
    xpReward: 60,
    minLevel: 4,
    maxLevel: 7,
  },

  // ========== LEVELS 5-7: Late Game ==========
  {
    type: 'demon',
    name: 'Demon',
    baseHp: 220,
    baseDamage: 38,
    damageType: 'attack',
    baseSpeed: 130,
    baseArmour: 18,
    baseMagicRes: 15,
    chaseRange: 350,
    attackRange: 55,
    attackSpeed: 1.1,
    color: '#8B0000',
    size: 28,
    xpReward: 75,
    minLevel: 5,
    maxLevel: 8,
  },
  {
    type: 'basilisk',
    name: 'Basilisk',
    baseHp: 300,
    baseDamage: 35,
    damageType: 'spell',
    baseSpeed: 90,
    baseArmour: 28,
    baseMagicRes: 22,
    chaseRange: 320,
    attackRange: 100,
    attackSpeed: 0.9,
    color: '#006400',
    size: 30,
    xpReward: 80,
    minLevel: 5,
    maxLevel: 8,
  },
  {
    type: 'minotaur',
    name: 'Minotaur',
    baseHp: 350,
    baseDamage: 45,
    damageType: 'attack',
    baseSpeed: 110,
    baseArmour: 30,
    baseMagicRes: 12,
    chaseRange: 310,
    attackRange: 65,
    attackSpeed: 0.7,
    color: '#8B4513',
    size: 34,
    xpReward: 90,
    minLevel: 5,
    maxLevel: 8,
  },

  // ========== LEVELS 7-9: End Game ==========
  {
    type: 'lich',
    name: 'Lich',
    baseHp: 280,
    baseDamage: 50,
    damageType: 'spell',
    baseSpeed: 100,
    baseArmour: 15,
    baseMagicRes: 40,
    chaseRange: 400,
    attackRange: 150,
    attackSpeed: 1.0,
    color: '#4B0082',
    size: 25,
    xpReward: 120,
    minLevel: 7,
    maxLevel: 10,
  },
  {
    type: 'drake',
    name: 'Drake',
    baseHp: 400,
    baseDamage: 48,
    damageType: 'spell',
    baseSpeed: 120,
    baseArmour: 35,
    baseMagicRes: 30,
    chaseRange: 380,
    attackRange: 130,
    attackSpeed: 0.8,
    color: '#FF4500',
    size: 38,
    xpReward: 140,
    minLevel: 7,
    maxLevel: 10,
  },
  {
    type: 'golem',
    name: 'Golem',
    baseHp: 500,
    baseDamage: 40,
    damageType: 'attack',
    baseSpeed: 50,
    baseArmour: 50,
    baseMagicRes: 35,
    chaseRange: 280,
    attackRange: 70,
    attackSpeed: 0.5,
    color: '#708090',
    size: 40,
    xpReward: 130,
    minLevel: 7,
    maxLevel: 10,
  },

  // ========== LEVELS 8-10: Boss Tier ==========
  {
    type: 'hydra',
    name: 'Hydra',
    baseHp: 600,
    baseDamage: 55,
    damageType: 'divine',
    baseSpeed: 80,
    baseArmour: 40,
    baseMagicRes: 40,
    chaseRange: 400,
    attackRange: 100,
    attackSpeed: 1.5,
    color: '#006400',
    size: 40,
    xpReward: 200,
    minLevel: 8,
    maxLevel: 10,
  },
];
